version: 2.1

executors:
  default_executor:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace

commands:
  restore_npm_cache:
    description: "Restore NPM cache"
    steps:
      - restore_cache:
          name: Restore cached NPM dependencies
          key: npm-dependency-cache-v1-{{ checksum "package-lock.json" }}

  run_npm_install:
    description: "Run NPM install"
    steps:
      - run:
          name: Run NPM install
          command: npm install

  save_npm_cache:
    description: "Save NPM cache"
    steps:
      - save_cache:
          name: Cache NPM dependencies
          key: npm-dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
# TODO: Uncomment to enable code coverage.
#  code_coverage:
#    executor: default_executor
#    steps:
#      - checkout
#      - restore_npm_cache
#      - run_npm_install
#      - run:
#          name: Download Code Climate Test Reporter
#          command: |
#            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#            chmod +x ./cc-test-reporter
#      - run:
#          name: Notify Code Climate Test Reporter - Before Build
#          command: ./cc-test-reporter before-build
#      - run:
#          name: Run code coverage
#          command: npm run test -- --coverage
#      - run:
#          name: Notify Code Climate Test Reporter - After Build
#          command: ./cc-test-reporter after-build --exit-code $?

  lint:
    executor: default_executor
    steps:
      - checkout
      - restore_npm_cache
      - run_npm_install
      - run:
          name: Run TypeScript linter
          command: npm run lint

  release:
    executor: default_executor
    steps:
      - checkout
      - restore_npm_cache
      - run_npm_install
      - run:
          name: Run semantic release
          command: npm run semantic-release

  unit_test:
    executor: default_executor
    steps:
      - checkout
      - restore_npm_cache
      - run_npm_install
      - run:
          name: Run unit test
          command: npm run test -- --runInBand --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "test_results/jest/unit_test_results.xml"
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results/jest

  update_npm_cache:
    executor: default_executor
    steps:
      - checkout
      - restore_npm_cache
      - run_npm_install
      - save_npm_cache

workflows:
  default_workflow:
    jobs:
      - update_npm_cache
      - lint:
          requires:
            - update_npm_cache
      - unit_test:
          requires:
            - update_npm_cache
# TODO: Uncomment to enable code coverage.
#      - code_coverage:
#          requires:
#            - lint
#            - unit_test
#          filters:
#            branches:
#              only: master
      - release:
          requires:
            - lint
            - unit_test
          filters:
            branches:
              only: master
